package visao;
import controle.CursoC;
import modelo.CursoM;
/**
 *
 * @author ra171050
 */
public class CadastroCursoV extends javax.swing.JInternalFrame {

    /**
     * Creates new form CadastroCursoV
     */
    public CadastroCursoV() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPcadastroCurso = new javax.swing.JPanel();
        jLcodigo = new javax.swing.JLabel();
        jLnome = new javax.swing.JLabel();
        jComboBoxTurno = new javax.swing.JComboBox<String>();
        jLturno = new javax.swing.JLabel();
        jTcodigo = new javax.swing.JTextField();
        jTnome = new javax.swing.JTextField();
        jPopcoes = new javax.swing.JPanel();
        jBcadastrar = new javax.swing.JButton();
        jBlimpar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);

        jPcadastroCurso.setBorder(javax.swing.BorderFactory.createTitledBorder("Cadastro Curso"));

        jLcodigo.setText("Código");

        jLnome.setText("Nome");

        jComboBoxTurno.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "s", "n" }));

        jLturno.setText("Turno");

        javax.swing.GroupLayout jPcadastroCursoLayout = new javax.swing.GroupLayout(jPcadastroCurso);
        jPcadastroCurso.setLayout(jPcadastroCursoLayout);
        jPcadastroCursoLayout.setHorizontalGroup(
            jPcadastroCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPcadastroCursoLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPcadastroCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLcodigo)
                    .addComponent(jLnome)
                    .addComponent(jLturno))
                .addGap(37, 37, 37)
                .addGroup(jPcadastroCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPcadastroCursoLayout.createSequentialGroup()
                        .addComponent(jComboBoxTurno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 243, Short.MAX_VALUE))
                    .addGroup(jPcadastroCursoLayout.createSequentialGroup()
                        .addGroup(jPcadastroCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTnome)
                            .addGroup(jPcadastroCursoLayout.createSequentialGroup()
                                .addComponent(jTcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        jPcadastroCursoLayout.setVerticalGroup(
            jPcadastroCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPcadastroCursoLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPcadastroCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLcodigo)
                    .addComponent(jTcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPcadastroCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLnome)
                    .addComponent(jTnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPcadastroCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLturno)
                    .addComponent(jComboBoxTurno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        jPopcoes.setBorder(javax.swing.BorderFactory.createTitledBorder("Opções"));

        jBcadastrar.setText("Cadastrar");
        jBcadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrar(evt);
            }
        });

        jBlimpar.setText("Limpar");
        jBlimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limparCurso(evt);
            }
        });

        javax.swing.GroupLayout jPopcoesLayout = new javax.swing.GroupLayout(jPopcoes);
        jPopcoes.setLayout(jPopcoesLayout);
        jPopcoesLayout.setHorizontalGroup(
            jPopcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPopcoesLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jBcadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addComponent(jBlimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
        );
        jPopcoesLayout.setVerticalGroup(
            jPopcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPopcoesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPopcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBcadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBlimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPopcoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPcadastroCurso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPcadastroCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPopcoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void limparCurso(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparCurso
        this.jTcodigo.setText("");
        this.jTnome.setText("");
        this.jComboBoxTurno.setSelectedIndex(0);    }//GEN-LAST:event_limparCurso

    private void cadastrar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrar

        int codigo  = Integer.parseInt(jTcodigo.getText());
        String nome = jTnome.getText(); 
        String turno = jComboBoxTurno.getSelectedItem().toString();
        CursoM cursoM = new CursoM(codigo, nome, turno);
        CursoC cursoC = new CursoC();
        cursoC.salvarCurso(cursoM);
    }//GEN-LAST:event_cadastrar


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBcadastrar;
    private javax.swing.JButton jBlimpar;
    private javax.swing.JComboBox<String> jComboBoxTurno;
    private javax.swing.JLabel jLcodigo;
    private javax.swing.JLabel jLnome;
    private javax.swing.JLabel jLturno;
    private javax.swing.JPanel jPcadastroCurso;
    private javax.swing.JPanel jPopcoes;
    private javax.swing.JTextField jTcodigo;
    private javax.swing.JTextField jTnome;
    // End of variables declaration//GEN-END:variables
}
