package visao;
import modelo.*;
import controle.*;
/**
 *
 * @author ra171050
 */
public class CadastrarProfessorV extends javax.swing.JInternalFrame {

    /**
     * Creates new form CadastrarProfessorV
     */
    public CadastrarProfessorV() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPcadastroCurso = new javax.swing.JPanel();
        jLcodigo = new javax.swing.JLabel();
        jTcodigo = new javax.swing.JTextField();
        jLanoInicio = new javax.swing.JLabel();
        jLnomeDoCurso = new javax.swing.JLabel();
        jLcargaHoraria = new javax.swing.JLabel();
        jLnumeroDeSemestre = new javax.swing.JLabel();
        jLcargaHorariaSemestral = new javax.swing.JLabel();
        jTanoInicio = new javax.swing.JTextField();
        jTnomeCurso = new javax.swing.JTextField();
        jTcargaHoraria = new javax.swing.JTextField();
        jTnumeroDeSemestre = new javax.swing.JTextField();
        jTcargaHorariaSemestral = new javax.swing.JTextField();
        jPopcoes = new javax.swing.JPanel();
        jBcadastrar = new javax.swing.JButton();
        limparDisciplina = new javax.swing.JButton();

        setClosable(true);

        jPcadastroCurso.setBorder(javax.swing.BorderFactory.createTitledBorder("Cadastro Grade"));

        jLcodigo.setText("Código");

        jLanoInicio.setText("Ano de Inicio");

        jLnomeDoCurso.setText("Nome do Curso");

        jLcargaHoraria.setText("Carga Horaria");

        jLnumeroDeSemestre.setText("Numero de Semestre");

        jLcargaHorariaSemestral.setText("Carga Horaria (semestral)");

        javax.swing.GroupLayout jPcadastroCursoLayout = new javax.swing.GroupLayout(jPcadastroCurso);
        jPcadastroCurso.setLayout(jPcadastroCursoLayout);
        jPcadastroCursoLayout.setHorizontalGroup(
            jPcadastroCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPcadastroCursoLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPcadastroCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPcadastroCursoLayout.createSequentialGroup()
                        .addGroup(jPcadastroCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLcodigo)
                            .addComponent(jLnomeDoCurso)
                            .addComponent(jLcargaHoraria))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPcadastroCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPcadastroCursoLayout.createSequentialGroup()
                                .addComponent(jTcargaHoraria, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLanoInicio)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTanoInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(16, 16, 16))
                            .addGroup(jPcadastroCursoLayout.createSequentialGroup()
                                .addGroup(jPcadastroCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTnomeCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPcadastroCursoLayout.createSequentialGroup()
                        .addGroup(jPcadastroCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPcadastroCursoLayout.createSequentialGroup()
                                .addComponent(jLcargaHorariaSemestral)
                                .addGap(18, 18, 18)
                                .addComponent(jTcargaHorariaSemestral, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPcadastroCursoLayout.createSequentialGroup()
                                .addComponent(jLnumeroDeSemestre)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTnumeroDeSemestre, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(12, 12, 12))))
        );
        jPcadastroCursoLayout.setVerticalGroup(
            jPcadastroCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPcadastroCursoLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPcadastroCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLcodigo)
                    .addComponent(jTcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPcadastroCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLnomeDoCurso)
                    .addComponent(jTnomeCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPcadastroCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLcargaHoraria)
                    .addComponent(jTcargaHoraria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTanoInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLanoInicio))
                .addGap(20, 20, 20)
                .addGroup(jPcadastroCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLnumeroDeSemestre)
                    .addComponent(jTnumeroDeSemestre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPcadastroCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLcargaHorariaSemestral)
                    .addComponent(jTcargaHorariaSemestral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jPopcoes.setBorder(javax.swing.BorderFactory.createTitledBorder("Opções"));

        jBcadastrar.setText("Cadastrar");
        jBcadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBcadastrarcadastrarGrade(evt);
            }
        });

        limparDisciplina.setText("Limpar");
        limparDisciplina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limparDisciplinalimparGrade(evt);
            }
        });

        javax.swing.GroupLayout jPopcoesLayout = new javax.swing.GroupLayout(jPopcoes);
        jPopcoes.setLayout(jPopcoesLayout);
        jPopcoesLayout.setHorizontalGroup(
            jPopcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPopcoesLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jBcadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(limparDisciplina, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
        );
        jPopcoesLayout.setVerticalGroup(
            jPopcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPopcoesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPopcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBcadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(limparDisciplina, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPopcoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPcadastroCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPcadastroCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPopcoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBcadastrarcadastrarGrade(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBcadastrarcadastrarGrade

        int codigo  = Integer.parseInt(jTcodigo.getText());
        int anoInicio = Integer.parseInt(jTanoInicio.getText());
        String curso = jTnomeCurso.getText();
        int cargaHoraria = Integer.parseInt(jTcargaHoraria.getText());
        int cargaHorariaSemestral = Integer.parseInt(jTcargaHorariaSemestral.getText());
        int numSemestre = Integer.parseInt(jTnumeroDeSemestre.getText());

        GradeM gradeM = new GradeM(codigo, anoInicio, curso, cargaHoraria, numSemestre, numSemestre);
        GradeC gradeC = new GradeC();
        gradeC.salvarGrade(gradeM);
    }//GEN-LAST:event_jBcadastrarcadastrarGrade

    private void limparDisciplinalimparGrade(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparDisciplinalimparGrade
        this.jTcodigo.setText("");
        this.jTanoInicio.setText("");
        this.jTnomeCurso.setText("");
        this.jTcargaHoraria.setText("");
        this.jTcargaHorariaSemestral.setText("");
        this.jTnumeroDeSemestre.setText("");
    }//GEN-LAST:event_limparDisciplinalimparGrade


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBcadastrar;
    private javax.swing.JLabel jLanoInicio;
    private javax.swing.JLabel jLcargaHoraria;
    private javax.swing.JLabel jLcargaHorariaSemestral;
    private javax.swing.JLabel jLcodigo;
    private javax.swing.JLabel jLnomeDoCurso;
    private javax.swing.JLabel jLnumeroDeSemestre;
    private javax.swing.JPanel jPcadastroCurso;
    private javax.swing.JPanel jPopcoes;
    private javax.swing.JTextField jTanoInicio;
    private javax.swing.JTextField jTcargaHoraria;
    private javax.swing.JTextField jTcargaHorariaSemestral;
    private javax.swing.JTextField jTcodigo;
    private javax.swing.JTextField jTnomeCurso;
    private javax.swing.JTextField jTnumeroDeSemestre;
    private javax.swing.JButton limparDisciplina;
    // End of variables declaration//GEN-END:variables
}
