package visao;
import controle.DisciplinaC;
import modelo.DisciplinaM;
/**
 *
 * @author ra171050
 */
public class CadastrarDisciplinaV extends javax.swing.JInternalFrame {

    /**
     * Creates new form CadastrarDisciplina
     */
    public CadastrarDisciplinaV() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPcadastroCurso = new javax.swing.JPanel();
        jLcodigo = new javax.swing.JLabel();
        jLnome = new javax.swing.JLabel();
        jTcodigo = new javax.swing.JTextField();
        jTnome = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTcargaHoraria = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTsemestre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTprofessor = new javax.swing.JTextField();
        jPopcoes = new javax.swing.JPanel();
        jBcadastrar = new javax.swing.JButton();
        limparDisciplina = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);

        jPcadastroCurso.setBorder(javax.swing.BorderFactory.createTitledBorder("Cadastro Disciplina"));

        jLcodigo.setText("Código");

        jLnome.setText("Nome");

        jLabel1.setText("Carga Horaria");

        jLabel2.setText("Semestre");

        jLabel3.setText("Professor");

        javax.swing.GroupLayout jPcadastroCursoLayout = new javax.swing.GroupLayout(jPcadastroCurso);
        jPcadastroCurso.setLayout(jPcadastroCursoLayout);
        jPcadastroCursoLayout.setHorizontalGroup(
            jPcadastroCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPcadastroCursoLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPcadastroCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPcadastroCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPcadastroCursoLayout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(43, 43, 43))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPcadastroCursoLayout.createSequentialGroup()
                            .addComponent(jLnome)
                            .addGap(77, 77, 77)))
                    .addGroup(jPcadastroCursoLayout.createSequentialGroup()
                        .addGroup(jPcadastroCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLcodigo)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(64, 64, 64)))
                .addGroup(jPcadastroCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTnome)
                    .addComponent(jTprofessor)
                    .addGroup(jPcadastroCursoLayout.createSequentialGroup()
                        .addGroup(jPcadastroCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTsemestre, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTcargaHoraria, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPcadastroCursoLayout.setVerticalGroup(
            jPcadastroCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPcadastroCursoLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPcadastroCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLcodigo)
                    .addComponent(jTcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPcadastroCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLnome)
                    .addComponent(jTnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPcadastroCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTprofessor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(jPcadastroCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTcargaHoraria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPcadastroCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTsemestre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPopcoes.setBorder(javax.swing.BorderFactory.createTitledBorder("Opções"));

        jBcadastrar.setText("Cadastrar");
        jBcadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarDisciplina(evt);
            }
        });

        limparDisciplina.setText("Limpar");
        limparDisciplina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limparDisciplinaDisciplina(evt);
            }
        });

        javax.swing.GroupLayout jPopcoesLayout = new javax.swing.GroupLayout(jPopcoes);
        jPopcoes.setLayout(jPopcoesLayout);
        jPopcoesLayout.setHorizontalGroup(
            jPopcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPopcoesLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jBcadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addComponent(limparDisciplina, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
        );
        jPopcoesLayout.setVerticalGroup(
            jPopcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPopcoesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPopcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBcadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(limparDisciplina, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPopcoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPcadastroCurso, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPcadastroCurso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPopcoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cadastrarDisciplina(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarDisciplina

        int codigo  = Integer.parseInt(jTcodigo.getText());
        String nome = jTnome.getText();        
        String professor = jTprofessor.getText();
        int cargaHoraria = Integer.parseInt(jTcargaHoraria.getText());
        int semestre = Integer.parseInt(jTsemestre.getText());
 
        DisciplinaM disciplinaM = new DisciplinaM(codigo, nome, cargaHoraria, semestre, professor);
        DisciplinaC disciplinaC = new DisciplinaC();
        disciplinaC.salvarDisciplina(disciplinaM);
    }//GEN-LAST:event_cadastrarDisciplina

    private void limparDisciplinaDisciplina(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparDisciplinaDisciplina
        this.jTcodigo.setText("");
        this.jTnome.setText("");
        this.jTcargaHoraria.setText("");
        this.jTprofessor.setText("");
        this.jTsemestre.setText("");
    }//GEN-LAST:event_limparDisciplinaDisciplina


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBcadastrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLcodigo;
    private javax.swing.JLabel jLnome;
    private javax.swing.JPanel jPcadastroCurso;
    private javax.swing.JPanel jPopcoes;
    private javax.swing.JTextField jTcargaHoraria;
    private javax.swing.JTextField jTcodigo;
    private javax.swing.JTextField jTnome;
    private javax.swing.JTextField jTprofessor;
    private javax.swing.JTextField jTsemestre;
    private javax.swing.JButton limparDisciplina;
    // End of variables declaration//GEN-END:variables
}
